const views=[...document.querySelectorAll("[data-view]")];
function showView(name){views.forEach(view=>view.classList.toggle("active",view.dataset.view===name));}
document.querySelectorAll("[data-open]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.open)));
document.querySelector("[data-gallery-lock]").addEventListener("click",()=>showView("gallery"));
const gate=document.querySelector("[data-gallery-gate]"),pin=document.querySelector("[data-gallery-pin]"),unlock=document.querySelector("[data-gallery-unlock]"),error=document.querySelector("[data-gallery-error]");
unlock.addEventListener("click",()=>{if(pin.value==="2013"){gate.classList.add("unlocked");error.textContent="";}else{error.textContent="Неверный код";pin.value="";pin.focus();}});
pin.addEventListener("keydown",e=>{if(e.key==="Enter")unlock.click();});
document.querySelectorAll("[data-back]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.back||"home")));
document.querySelector("[data-home]").addEventListener("click",()=>showView("home"));
function updateClock(){const now=new Date();document.querySelector("#clock").textContent=now.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});}
updateClock();setInterval(updateClock,30000);
const viewer=document.querySelector("[data-photo-viewer]"),viewerImage=document.querySelector("[data-viewer-image]"),viewerDate=document.querySelector("[data-viewer-date]");
document.querySelectorAll("[data-photo]").forEach(photo=>photo.addEventListener("click",()=>{viewerImage.src=photo.dataset.photo;viewerDate.textContent=photo.dataset.date;viewer.classList.add("open");}));
document.querySelector("[data-viewer-close]").addEventListener("click",()=>{viewer.classList.remove("open");viewerImage.src="";});

const mapCanvas=document.querySelector("[data-map-canvas]"),mapTransform=document.querySelector("[data-map-transform]");
if(mapCanvas&&mapTransform){let scale=1,x=0,y=0,pointers=new Map(),lastDist=0,lastMid=null;const clamp=v=>Math.max(1,Math.min(4,v));const render=()=>mapTransform.style.transform=`translate(${x}px,${y}px) scale(${scale})`;const reset=()=>{scale=1;x=0;y=0;render()};document.querySelector("[data-map-zoom-in]").addEventListener("click",()=>{scale=clamp(scale+.35);render()});document.querySelector("[data-map-zoom-out]").addEventListener("click",()=>{scale=clamp(scale-.35);if(scale===1){x=0;y=0}render()});document.querySelector("[data-map-reset]").addEventListener("click",reset);mapCanvas.addEventListener("wheel",e=>{e.preventDefault();scale=clamp(scale+(e.deltaY<0?.2:-.2));if(scale===1){x=0;y=0}render()},{passive:false});mapCanvas.addEventListener("pointerdown",e=>{mapCanvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});mapCanvas.classList.add("dragging")});mapCanvas.addEventListener("pointermove",e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const pts=[...pointers.values()];if(pts.length===1&&scale>1){x+=e.clientX-old.x;y+=e.clientY-old.y;render()}else if(pts.length>=2){const [a,b]=pts,dist=Math.hypot(a.x-b.x,a.y-b.y),mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(lastDist){scale=clamp(scale*dist/lastDist);if(lastMid){x+=mid.x-lastMid.x;y+=mid.y-lastMid.y}render()}lastDist=dist;lastMid=mid}});const up=e=>{pointers.delete(e.pointerId);if(pointers.size<2){lastDist=0;lastMid=null}if(!pointers.size)mapCanvas.classList.remove("dragging")};mapCanvas.addEventListener("pointerup",up);mapCanvas.addEventListener("pointercancel",up);mapCanvas.addEventListener("dblclick",()=>{scale=clamp(scale+.5);render()});render()}
